apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mathiscode/k8s-boilerplate-service-auth
      context: ./packages/auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mathiscode/k8s-boilerplate-client
      context: ./packages/client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts*'
            dest: .
    - image: mathiscode/k8s-boilerplate-service-tickets
      context: ./packages/tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: mathiscode/k8s-boilerplate-service-orders
      context: ./packages/orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
