apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      containers:
        - name: expiration
          image: mathiscode/k8s-boilerplate-service-expiration
          env:
            - name: REDIS_HOST
              value: expiration-redis-srv
            - name: NATS_URL
              value: http://nats-srv:4222
            - name: NATS_CLUSTER_ID
              value: next-k8s-nats
            - name:  NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
